get:
  tags:
    - Product
  summary: Get product by ID
  description: |
    Get all products
  operationId: getProductByID
  security: []
  parameters:
    - name: id
      in: path
      required: true
      schema:
        $ref: ../components/parameters/id.yaml
  responses:
    "200":
      description: Success
      content:
        application/json:
          schema:
            type: object
            items:
              $ref: ../components/schemas/Product.yaml
            example:
              id: 1
              thumbnail: https://picsum.photos/200/300
              title: پکیج بورس ایران
              features:
                [
                  "اخبار و اطلاع رسانی دقیق از مسائل جزئی و اساسی بورس ایران",
                  "تحلیل پایه ای و تخصصی و همچنین سیگنال VIP",
                ]
              price: 49.99
              offPrice: 39.99
              exclusive: true
    "404":
      description: No product found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yaml
          examples:
            notFound:
              summary: No product found
              description: did not find any product
              value:
                code: 404
                message: "no product found"
