get:
  tags:
    - Product
  summary: Get products
  description: |
    Get all products
  operationId: getProducts
  security: []
  responses:
    "200":
      description: Success
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/Product.yaml
            example:
              - id: 1
                thumbnail: https://picsum.photos/200/300
                title: پکیج بورس ایران
                features:
                  [
                    "اخبار و اطلاع رسانی دقیق از مسائل جزئی و اساسی بورس ایران",
                    "تحلیل پایه ای و تخصصی و همچنین سیگنال VIP",
                  ]
                price: 49.99
                offPrice: 39.99
              - id: 2
                thumbnail: https://picsum.photos/200/300
                title: پکیج فارکس و بورس خارجی
                features:
                  [
                    "اخبار و اطلاع رسانی دقیق از مسائل جزئی و اساسی بورس ایران",
                    "تحلیل پایه ای و تخصصی و همچنین سیگنال VIP",
                  ]
                price: 49.99
              - id: 3
                thumbnail: https://picsum.photos/200/300
                title: پکیج بازار کریپتو
                features:
                  [
                    "اخبار و اطلاع رسانی دقیق از مسائل جزئی و اساسی بورس ایران",
                    "تحلیل پایه ای و تخصصی و همچنین سیگنال VIP",
                  ]
                price: 49.99
              - id: 4
                thumbnail: https://picsum.photos/200/300
                title: پکیج دلار و طلا
                features:
                  [
                    "اخبار و اطلاع رسانی دقیق از مسائل جزئی و اساسی بورس ایران",
                    "تحلیل پایه ای و تخصصی و همچنین سیگنال VIP",
                  ]
                price: 49.99
                offPrice: 39.99
              - id: 5
                thumbnail: https://picsum.photos/200/300
                title: پکیج بورس ایران ۲
                features:
                  [
                    "اخبار و اطلاع رسانی دقیق از مسائل جزئی و اساسی بورس ایران",
                    "تحلیل پایه ای و تخصصی و همچنین سیگنال VIP",
                  ]
                price: 49.99
                offPrice: 39.99

    "404":
      description: No product found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Error.yaml
          examples:
            notFound:
              summary: No product found
              description: did not find any product
              value:
                code: 404
                message: "no product found"
