# See https://redoc.ly/docs/cli/configuration/ for more information.
extends:
  - recommended

apis:
  core@v1:
    root: openapi/openapi.yaml
    rules: 
      no-ambiguous-paths: error
      no-unused-components: warn

      
    theme:
      openapi:
        hideLogo: true
          

theme:
  openapi:
    schemaExpansionLevel: 2
    generateCodeSamples:
      languages:
        - lang: curl
        - lang: Python

