openapi: 3.1.0
info:
  version: 0.1.0
  title: sigloyland
  termsOfService: "https://sigloyland.com/terms/"
  contact:
    email: contact@sigloyland.com
    url: "http://sigloyland.com/contact"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "images/Logo.svg"
  description: >
    Documentation for **sigloyland** API

tags:
  - name: User
    description: Operations about user
servers:
  - url: "https://api.sigloyland.com"
  - url: "https://staging.api.sigloyland.com"
paths:
  "/user/verify":
    $ref: paths/user@verify.yaml
  "/user/entry":
    $ref: paths/user@entry.yaml
  "/user/refresh":
    $ref: paths/user@refresh-token.yaml
  "/user/forget-password":
    $ref: paths/user@forget-password.yaml
  "/user/forget-password/verify":
    $ref: paths/user@forget-password@verify.yaml
  "/user/reset-password":
    $ref: paths/user@reset-password.yaml
  "/user":
    $ref: paths/user.yaml
  "/product/all":
    $ref: paths/product@all.yaml
  "/product/{id}":
    $ref: paths/product@{id}.yaml
  "/cart":
    $ref: paths/cart.yaml
  "/cart/{productID}":
    $ref: paths/cart@{productID}.yaml
  "/payment/all":
    $ref: paths/payment@all.yaml
  "/payment":
    $ref: paths/payment.yaml

components:
  securitySchemes:
    jwt:
      $ref: components/securitySchemes/jwt.yaml
