openapi: 3.1.0
info:
  version: 0.1.0
  title: sigloyland
  termsOfService: "https://sigloyland.com/terms/"
  contact:
    email: contact@sigloyland.com
    url: "http://sigloyland.com/contact"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "images/Logo.svg"
  description: >
    Documentation for **sigloyland** API

tags:
  - name: User
    description: Operations about user
servers:
  - url: "http://sigloyland.com/api/v1"
  - url: "https://sigloyland.com/api/v1"
paths:
  "/user/register":
    $ref: paths/user@register.yaml
  "/user/login":
    $ref: paths/user@login.yaml
  "/user/refresh":
    $ref: paths/user@refresh.yaml
  "/user/verify":
    $ref: paths/user@verify.yaml
  "/user":
    $ref: "paths/user.yaml"
  "/products":
    $ref: paths/products.yaml
components:
  securitySchemes:
    oauth2:
      $ref: components/securitySchemes/oauth2.yaml
    jwt:
      $ref: components/securitySchemes/jwt.yaml
