type: object
properties:
  id:
    description: Product id
    $ref: ../parameters/id.yaml
    example: 1
  thumbnail:
    description: Product thumbnail
    type: string
    example: https://sigloyland.com/static/thumbnail-1
  title:
    description: Product titile
    type: string
    example: Some Title
  features:
    description: Product features
    type: array
    example: ["feature 1", "feature 2"]
  price:
    description: Product price
    type: number
    format: double
    example: 49.99
  offPrice:
    description: Product off price
    type: number
    format: double
    example: 39.99
  exclusive:
    description: if this product is exclusive for adding to the cart
    type: boolean
    example: false

    
